/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clases;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import static java.awt.SystemColor.menu;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTabbedPane;
import modulos.EstoqueNioaque; //importando minha classe do pacote modulos
import modulos.JardimMS; // importando meu pacote com minha clase
import modulos.Bonito;
import modulos.Maracaju;
import modulos.sidrolandia;
import modulos.Campogrande;


/**
 *
 * @author gerso
 */
public class Menu extends javax.swing.JFrame {
    private static Menu instance;
    private EstoqueNioaque estoqueNioaque;
    private JardimMS jardimMS;
    private Bonito bonito;
    private Maracaju maracaju;
    private sidrolandia sidrolandia;
    private Campogrande campogrande;
    
    /**
     * Creates new form Menu
     */   
    //clase menu
    public Menu() {
         // Carrega o ícone personalizado
        initComponents();
        
        // Centraliza a janela
        setLocationRelativeTo(null);
        
        setTitle("Controle de Estoque"); // Define o título da janela
        
         // Carrega o ícone personalizado
      // Define o ícone da janela
        ImageIcon icon = new ImageIcon(getClass().getResource("/icones/cidade.png"));
        setIconImage(icon.getImage());
        
       // Definir o layout do contentPane como GridBagLayout
        getContentPane().setLayout(new GridBagLayout());
       

        // Adicionar os componentes ao contentPane usando GridBagConstraints
        GridBagConstraints gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5); // Espaçamento entre os componentes

        /*getContentPane().add(EstoqueNioaque gridBagConstraints);*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl5 = new javax.swing.JLabel();
        FrameMenu0 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ItenMenuNioaque = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/21133731_2108.w023.n001.937B.p1.937.jpg"))); // NOI18N
        lbl5.setToolTipText("");
        getContentPane().add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 870, 400));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/definicoes.png"))); // NOI18N
        jMenu1.setText("menu");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/fechar_24_24x1.png"))); // NOI18N
        jMenuItem1.setText("sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        FrameMenu0.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/investimento.png"))); // NOI18N
        jMenu2.setText("estoque 1");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        ItenMenuNioaque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/dinosaur.png"))); // NOI18N
        ItenMenuNioaque.setText("Nioaque");
        ItenMenuNioaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItenMenuNioaqueActionPerformed(evt);
            }
        });
        jMenu2.add(ItenMenuNioaque);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cidade.png"))); // NOI18N
        jMenuItem2.setText("Jardim");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salsicha.png"))); // NOI18N
        jMenuItem3.setText("Maracaju");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/parque-natural.png"))); // NOI18N
        jMenuItem5.setText("Bonito");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pin-de-localizacao.png"))); // NOI18N
        jMenuItem4.setText("Sidrolandia");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        FrameMenu0.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/estoque1.png"))); // NOI18N
        jMenu3.setText("Estoque 2");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cidade2.png"))); // NOI18N
        jMenuItem6.setText("Campo Grande");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        FrameMenu0.add(jMenu3);

        setJMenuBar(FrameMenu0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItenMenuNioaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItenMenuNioaqueActionPerformed
        // TODO add your handling code here:
        
        if (estoqueNioaque == null) { // funcao que verifica se o classe ja esta aberta ou nao 
        estoqueNioaque = new EstoqueNioaque();
        estoqueNioaque.addWindowListener(new WindowAdapter() {
            
            public void windowClosed(WindowEvent e) {
                estoqueNioaque = null;
                new EstoqueNioaque().dispose();
            }
        });
    }
    estoqueNioaque.setVisible(true);
       
    }//GEN-LAST:event_ItenMenuNioaqueActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
   if (jardimMS == null) {
        jardimMS = new JardimMS();
        jardimMS.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                jardimMS = null;
                new JardimMS().dispose();
            }
        });
    }
    jardimMS.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
       if (bonito == null) {
        bonito = new Bonito();
        bonito.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                bonito = null;
                new Bonito().dispose();
            }
        });
    }
    bonito.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if (maracaju == null) {
        maracaju = new Maracaju();
        maracaju.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                maracaju = null;
                new Maracaju().dispose();
            }
        });
    }
    maracaju.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        if (sidrolandia == null) {
        sidrolandia = new sidrolandia();
        sidrolandia.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                sidrolandia = null;
                 new sidrolandia().dispose();
            }
        });
    }
    sidrolandia.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new EstoqueNioaque().dispose();;
        new JardimMS().dispose();
        new Bonito().dispose();
        new Maracaju().dispose();
        new sidrolandia().dispose();
        new Campogrande().dispose();
          // Fechar outras janelas abertas, se existirem
    if (estoqueNioaque != null) {
        estoqueNioaque.dispose();
    }
    if (jardimMS != null) {
        jardimMS.dispose();
    }
    if (bonito != null) {
        bonito.dispose();
    }
    if (maracaju != null) {
        maracaju.dispose();
    }
    if (sidrolandia != null) {
        sidrolandia.dispose();
    }
    if (campogrande != null) {
        campogrande.dispose();
    }

    // Encerrar a aplicação completamente
    System.exit(0);
    
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        if (campogrande == null) {
        campogrande = new Campogrande();
        campogrande.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                campogrande = null;
                 new sidrolandia().dispose();
            }
        });
    }
    campogrande.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
                    if (instance == null) {
                  // Se não foi criada, crie uma nova instância e armazene a referência
                    instance = new Menu();
                    } else {
                       // Se já foi criada, traga a instância existente para a frente
                       instance.toFront();
                   }
               // Definir ícone da janela
        ImageIcon icon = new ImageIcon(getClass().getResource("/icones/cidade.png"));
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar FrameMenu0;
    private javax.swing.JMenuItem ItenMenuNioaque;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JLabel lbl5;
    // End of variables declaration//GEN-END:variables
}